-- CaseMYP workflow hardening
-- Safe phase: additive schema changes, immutable audit trail, and market archive.
-- This migration does not delete production data and does not enable the new
-- Supabase Auth policies. Run the Auth cutover separately after account linking.

begin;

alter table public.cases
  add column if not exists version integer not null default 1,
  add column if not exists next_action text,
  add column if not exists next_action_at timestamptz,
  add column if not exists assigned_at timestamptz,
  add column if not exists assigned_by text,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text,
  add column if not exists delete_reason text;

alter table public.bookings
  add column if not exists version integer not null default 1,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table public.standalone_cases
  add column if not exists version integer not null default 1,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table public.case_notes
  add column if not exists deleted_by text;

alter table public.case_followups
  add column if not exists deleted_by text;

create index if not exists cases_active_sales_updated_idx
  on public.cases (sales, updatedat desc)
  where deleted_at is null;
create index if not exists cases_unassigned_idx
  on public.cases (updatedat desc)
  where deleted_at is null and (sales is null or btrim(sales) = '' or sales = 'รอมอบหมาย');
create index if not exists cases_next_action_idx
  on public.cases (next_action_at)
  where deleted_at is null and next_action_at is not null;
create index if not exists cases_deleted_at_idx
  on public.cases (deleted_at)
  where deleted_at is not null;
create index if not exists bookings_deleted_at_idx
  on public.bookings (deleted_at)
  where deleted_at is not null;
create index if not exists standalone_cases_deleted_at_idx
  on public.standalone_cases (deleted_at)
  where deleted_at is not null;

-- Preserve legacy market history in dedicated read-only archive tables.
create table if not exists public.market_archive
  (like public.market including defaults including constraints including indexes);
create table if not exists public.claimedcases_archive
  (like public.claimedcases including defaults including constraints including indexes);

insert into public.market_archive
select * from public.market
on conflict do nothing;

insert into public.claimedcases_archive
select * from public.claimedcases
on conflict do nothing;

comment on table public.market_archive is
  'Read-only historical snapshot created when the market workflow was retired.';
comment on table public.claimedcases_archive is
  'Read-only historical snapshot created when the market workflow was retired.';

revoke insert, update, delete, truncate on public.market_archive from anon, authenticated;
revoke insert, update, delete, truncate on public.claimedcases_archive from anon, authenticated;

-- The old live tables remain readable for verification/rollback but client writes stop.
revoke insert, update, delete, truncate on public.market from anon, authenticated;
revoke insert, update, delete, truncate on public.claimedcases from anon, authenticated;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_uid uuid,
  actor_label text not null default 'system',
  table_name text not null,
  record_key text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  old_data jsonb,
  new_data jsonb
);

create index if not exists audit_log_record_idx
  on public.audit_log (table_name, record_key, occurred_at desc);
create index if not exists audit_log_actor_idx
  on public.audit_log (actor_uid, occurred_at desc);

alter table public.audit_log enable row level security;

drop policy if exists "authenticated can read audit log" on public.audit_log;
create policy "authenticated can read audit log"
  on public.audit_log for select
  to authenticated
  using (true);

revoke update, delete, truncate on public.audit_log from anon, authenticated;
grant select on public.audit_log to authenticated;

create or replace function public.record_case_myp_audit()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  old_row jsonb;
  new_row jsonb;
  record_id text;
begin
  old_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  record_id := coalesce(
    new_row ->> 'caseid', old_row ->> 'caseid',
    new_row ->> 'id', old_row ->> 'id',
    'unknown'
  );

  insert into public.audit_log (
    actor_uid, actor_label, table_name, record_key, operation, old_data, new_data
  )
  values (
    auth.uid(),
    coalesce(auth.uid()::text, 'legacy-client'),
    tg_table_name,
    record_id,
    tg_op,
    old_row,
    new_row
  );

  return coalesce(new, old);
end;
$$;

drop trigger if exists cases_immutable_audit on public.cases;
create trigger cases_immutable_audit
after insert or update or delete on public.cases
for each row execute function public.record_case_myp_audit();

drop trigger if exists bookings_immutable_audit on public.bookings;
create trigger bookings_immutable_audit
after insert or update or delete on public.bookings
for each row execute function public.record_case_myp_audit();

drop trigger if exists standalone_cases_immutable_audit on public.standalone_cases;
create trigger standalone_cases_immutable_audit
after insert or update or delete on public.standalone_cases
for each row execute function public.record_case_myp_audit();

-- Intentionally not scheduled automatically. Run only after a verified backup.
create or replace function public.purge_case_myp_trash(retention_days integer default 30)
returns table (table_name text, deleted_count bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  cutoff timestamptz := now() - make_interval(days => greatest(retention_days, 30));
  affected bigint;
begin
  delete from public.bookings where deleted_at < cutoff;
  get diagnostics affected = row_count;
  return query select 'bookings'::text, affected;

  delete from public.standalone_cases where deleted_at < cutoff;
  get diagnostics affected = row_count;
  return query select 'standalone_cases'::text, affected;

  delete from public.cases where deleted_at < cutoff;
  get diagnostics affected = row_count;
  return query select 'cases'::text, affected;
end;
$$;

revoke all on function public.purge_case_myp_trash(integer) from public, anon, authenticated;

commit;
