-- CaseMYP staging compatibility schema
-- IMPORTANT: Run only in the isolated umMYP-staging Supabase project.
-- This intentionally contains no production customer data and no real users.
--
-- Purpose:
-- 1. Reproduce the current application's table contract for safe preview testing.
-- 2. Add missing primary keys, identity defaults, uniqueness, and query indexes.
-- 3. Keep temporary legacy API compatibility until Supabase Auth migration is ready.
--
-- This is NOT the final production security migration. The temporary RLS policies
-- below allow the current anonymous client to operate in staging with synthetic data.

begin;

create extension if not exists pgcrypto;

create table if not exists public.bank_logos (
  id integer generated by default as identity primary key,
  logo_url text,
  name text unique
);

create table if not exists public.cases (
  attachment text,
  caseid text primary key,
  contact text,
  createdat text,
  customername text,
  market boolean default false,
  report text,
  sales text,
  sent text default 'ปกติ',
  status text default 'รอข้อมูล',
  updatedat text
);

create table if not exists public.bookings (
  ads text,
  brand text,
  caseid text,
  createdat text,
  customer text,
  facebook text,
  id bigint generated by default as identity primary key,
  model text,
  note text,
  plate text,
  sales text,
  status text default 'จองแล้ว'
);

create table if not exists public.case_followups (
  caseid text not null,
  createdat text not null default '',
  customername text not null default '',
  deletedat text,
  doneat text not null default '',
  due_date text not null default '',
  id bigint generated by default as identity primary key,
  note text not null default '',
  notified_on text not null default '',
  sales text not null default '',
  status text not null default 'pending'
);

create table if not exists public.case_notes (
  caseid text not null,
  createdat text not null default '',
  deletedat text,
  id bigint generated by default as identity primary key,
  note text not null default '',
  sales text not null default ''
);

create table if not exists public.claimedcases (
  id bigint generated by default as identity primary key,
  assignedat text,
  caseid text,
  contact text,
  customername text,
  fromsales text,
  newstatus text,
  notes text,
  report text,
  sale text,
  status text,
  constraint claimedcases_caseid_key unique (caseid)
);

create table if not exists public.fcm_tokens (
  id integer generated by default as identity primary key,
  platform text default 'web',
  sales_name text,
  token text not null,
  updated_at timestamptz default now(),
  userid text not null unique
);

create table if not exists public.history (
  id bigint generated by default as identity primary key,
  action text,
  caseid text,
  createdat text,
  detail text,
  sales text
);

create table if not exists public.market (
  contact text,
  contact_by text,
  expiredsales text,
  id text primary key,
  name text,
  old_sales text,
  poolstatus text default 'เปิด',
  report text,
  status text
);

create table if not exists public.notifications (
  caseid text,
  createdat text,
  id integer generated by default as identity primary key,
  message text,
  sales text,
  status text default 'unread'
);

create table if not exists public.profile_images (
  image_url text,
  name text not null,
  subtitle text,
  title text,
  type text not null,
  updated_at timestamptz default now(),
  primary key (type, name),
  constraint profile_images_type_check
    check (type in ('branch', 'vehicle'))
);

create table if not exists public.standalone_cases (
  case_type text not null,
  created_at timestamptz not null default now(),
  created_by text default '',
  id bigint generated by default as identity primary key,
  name text not null default '',
  report text default '',
  sales text default '',
  status text default 'รอข้อมูล',
  updated_at timestamptz not null default now(),
  constraint standalone_cases_case_type_check
    check (case_type in ('private', 'line_oa'))
);

create table if not exists public.targets (
  created_at timestamptz default now(),
  id bigint generated by default as identity primary key,
  month_key text not null,
  sales_name text not null,
  target_value integer default 0,
  updated_at timestamptz default now(),
  constraint targets_sales_name_month_key_key
    unique (sales_name, month_key)
);

create table if not exists public.users (
  avatar text,
  line_user_id text default '',
  name text,
  password text,
  role text default 'Sales',
  startdate text,
  status text default 'active',
  userid text primary key,
  username text unique
);

create index if not exists bookings_caseid_idx
  on public.bookings (caseid);
create index if not exists bookings_createdat_idx
  on public.bookings (createdat desc);
create index if not exists case_followups_caseid_idx
  on public.case_followups (caseid);
create index if not exists case_followups_sales_due_idx
  on public.case_followups (sales, due_date);
create index if not exists case_followups_status_idx
  on public.case_followups (status);
create index if not exists case_notes_caseid_idx
  on public.case_notes (caseid);
create index if not exists case_notes_sales_idx
  on public.case_notes (sales);
create index if not exists cases_sales_idx
  on public.cases (sales);
create index if not exists cases_status_idx
  on public.cases (status);
create index if not exists cases_market_idx
  on public.cases (market);
create index if not exists claimedcases_sale_idx
  on public.claimedcases (sale);
create index if not exists history_caseid_idx
  on public.history (caseid);
create index if not exists market_poolstatus_idx
  on public.market (poolstatus);
create index if not exists notifications_sales_status_idx
  on public.notifications (sales, status, id desc);
create index if not exists standalone_cases_sales_idx
  on public.standalone_cases (sales);
create index if not exists standalone_cases_type_created_idx
  on public.standalone_cases (case_type, created_at desc);
create index if not exists users_role_status_idx
  on public.users (role, status);

alter table public.bank_logos enable row level security;
alter table public.bookings enable row level security;
alter table public.case_followups enable row level security;
alter table public.case_notes enable row level security;
alter table public.cases enable row level security;
alter table public.claimedcases enable row level security;
alter table public.fcm_tokens enable row level security;
alter table public.history enable row level security;
alter table public.market enable row level security;
alter table public.notifications enable row level security;
alter table public.profile_images enable row level security;
alter table public.standalone_cases enable row level security;
alter table public.targets enable row level security;
alter table public.users enable row level security;

-- Temporary staging-only compatibility policies.
-- The final Auth migration will replace these with role- and owner-scoped policies.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'bank_logos',
    'bookings',
    'case_followups',
    'case_notes',
    'cases',
    'claimedcases',
    'fcm_tokens',
    'history',
    'market',
    'notifications',
    'profile_images',
    'standalone_cases',
    'targets',
    'users'
  ]
  loop
    execute format(
      'drop policy if exists %I on public.%I',
      'staging_legacy_compatibility',
      table_name
    );
    execute format(
      'create policy %I on public.%I for all to anon, authenticated using (true) with check (true)',
      'staging_legacy_compatibility',
      table_name
    );
  end loop;
end
$$;

revoke all on all tables in schema public from anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete
  on all tables in schema public
  to anon, authenticated;
grant usage, select
  on all sequences in schema public
  to anon, authenticated;

commit;

select
  count(*) filter (where table_schema = 'public') as public_table_count,
  count(*) filter (
    where table_schema = 'public'
      and table_name in (
        'bank_logos', 'bookings', 'case_followups', 'case_notes',
        'cases', 'claimedcases', 'fcm_tokens', 'history', 'market',
        'notifications', 'profile_images', 'standalone_cases',
        'targets', 'users'
      )
  ) as expected_table_count
from information_schema.tables;
