-- Run in umMYP-staging after 01_compatibility_schema.sql.
-- Supabase SQL Editor does not support psql \ir, so this staging script is
-- intentionally self-contained.

begin;

alter table public.cases
  add column if not exists version integer not null default 1,
  add column if not exists next_action text,
  add column if not exists next_action_at timestamptz,
  add column if not exists assigned_at timestamptz,
  add column if not exists assigned_by text,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text,
  add column if not exists delete_reason text;

alter table public.bookings
  add column if not exists version integer not null default 1,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table public.standalone_cases
  add column if not exists version integer not null default 1,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by text;

alter table public.case_notes add column if not exists deleted_by text;
alter table public.case_followups add column if not exists deleted_by text;

create index if not exists cases_active_sales_updated_idx
  on public.cases (sales, updatedat desc) where deleted_at is null;
create index if not exists cases_unassigned_idx
  on public.cases (updatedat desc)
  where deleted_at is null and (sales is null or btrim(sales) = '' or sales = 'รอมอบหมาย');
create index if not exists cases_next_action_idx
  on public.cases (next_action_at)
  where deleted_at is null and next_action_at is not null;
create index if not exists cases_deleted_at_idx
  on public.cases (deleted_at) where deleted_at is not null;
create index if not exists bookings_deleted_at_idx
  on public.bookings (deleted_at) where deleted_at is not null;
create index if not exists standalone_cases_deleted_at_idx
  on public.standalone_cases (deleted_at) where deleted_at is not null;

create table if not exists public.market_archive
  (like public.market including defaults including constraints including indexes);
create table if not exists public.claimedcases_archive
  (like public.claimedcases including defaults including constraints including indexes);
insert into public.market_archive select * from public.market on conflict do nothing;
insert into public.claimedcases_archive select * from public.claimedcases on conflict do nothing;
revoke insert, update, delete, truncate on public.market_archive from anon, authenticated;
revoke insert, update, delete, truncate on public.claimedcases_archive from anon, authenticated;
revoke insert, update, delete, truncate on public.market from anon, authenticated;
revoke insert, update, delete, truncate on public.claimedcases from anon, authenticated;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_uid uuid,
  actor_label text not null default 'system',
  table_name text not null,
  record_key text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  old_data jsonb,
  new_data jsonb
);

create index if not exists audit_log_record_idx
  on public.audit_log (table_name, record_key, occurred_at desc);
alter table public.audit_log enable row level security;
drop policy if exists "staging authenticated reads audit log" on public.audit_log;
create policy "staging authenticated reads audit log"
  on public.audit_log for select to authenticated using (true);
revoke update, delete, truncate on public.audit_log from anon, authenticated;

create or replace function public.record_case_myp_audit()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  old_row jsonb;
  new_row jsonb;
begin
  old_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  insert into public.audit_log (
    actor_uid, actor_label, table_name, record_key, operation, old_data, new_data
  )
  values (
    auth.uid(),
    coalesce(auth.uid()::text, 'staging-legacy-client'),
    tg_table_name,
    coalesce(
      new_row ->> 'caseid', old_row ->> 'caseid',
      new_row ->> 'id', old_row ->> 'id', 'unknown'
    ),
    tg_op,
    old_row,
    new_row
  );
  return coalesce(new, old);
end;
$$;

drop trigger if exists cases_immutable_audit on public.cases;
create trigger cases_immutable_audit
after insert or update or delete on public.cases
for each row execute function public.record_case_myp_audit();
drop trigger if exists bookings_immutable_audit on public.bookings;
create trigger bookings_immutable_audit
after insert or update or delete on public.bookings
for each row execute function public.record_case_myp_audit();
drop trigger if exists standalone_cases_immutable_audit on public.standalone_cases;
create trigger standalone_cases_immutable_audit
after insert or update or delete on public.standalone_cases
for each row execute function public.record_case_myp_audit();

-- Keep temporary synthetic-data access while preview testing.
drop policy if exists "allow all" on public.audit_log;
create policy "allow all" on public.audit_log
  for select to public using (true);

commit;
